---
- name: Create VM
  hosts: localhost
  gather_facts: true

  vars_files:
    - config.yml

  tasks:
    - name: Create tmp to tail build logs.
      ansible.builtin.tempfile:
        state: file
        suffix: build_logs
      register: log_stream

    - name: Build logs streaming to
      debug:
        msg: "{{ log_stream.path }}"

    - name: Build base image
      ansible.builtin.shell:
        cmd: |
          packer init {{ base_image.type }}.pkr.hcl
          packer build -color=true -var 'version={{ base_image.version }}' -var 'checksum={{ base_image.checksum }}' {{ base_image.type }}.pkr.hcl | tee {{ log_stream.path }}
        chdir: images/
